name: Build and Test

on:
  push:
    branches:
      - main
      - releases/*
    paths:
      - 'src/**'
      - 'workflows/build-and-test.yml'
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_CONFIGURATION: Release
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [ '6.0.x', '7.0.x' ]
        solution:
          - "src/AdminApp.Extensions.EmailSending.Abstractions/AdminApp.Extensions.EmailSending.Abstractions.sln"
          - "src/AdminApp.Extensions.EmailSending/AdminApp.Extensions.EmailSending.sln"
          - "src/AdminApp.Extensions.EmailSending.Mailgun/AdminApp.Extensions.EmailSending.Mailgun.sln"
          - "src/AdminApp.Extensions.EmailSending.SendGrid/AdminApp.Extensions.EmailSending.SendGrid.sln"
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Dotnet Restore
      run: dotnet restore ${{ matrix.solution }}
    - name: Build
      run: dotnet build ${{ matrix.solution }} --configuration ${{ matrix.BUILD_CONFIGURATION }} --no-restore
